name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hi there ! Thank you so much for raising an issue and helping Bhashaflix become better.'' first issue'
        pr-message: 'Hi there ! Thank you for contributing to Bhashaflix. We will approve your request as soon as possible.'' first pr'
